const route=require("express").Router()
const UserProfile=require("../controllers/UserProfile.Controller")
const Hobbies=require("../controllers/Hobbie.controller")
const SocialMedia=require("../controllers/SocialMediaController")
const ImagesUser=require("../controllers/Images.controller")
const {verifyToken}=require("../middlewares")
route.post("/profileimage",verifyToken,UserProfile.addimageprofile)
route.get("/profileimage",verifyToken,UserProfile.getprofileImageb)
route.post("/profiledescription",verifyToken,UserProfile.adddescription)
route.patch("/profiledescription",verifyToken,UserProfile.updatedescription)
route.get("/profiledescription",verifyToken,UserProfile.getdescription)
route.get("/profilegetinteresofexpert",verifyToken,UserProfile.getinteresofselect)
route.post("/profilegetinteresofexpert",verifyToken,UserProfile.addinterestOrExpert)
route.delete("/profilegetinteresofexpert",verifyToken,UserProfile.deleteexpertORinterest)
route.get("/profilegetinteresofexpert/expertofus",verifyToken,UserProfile.getinteresorexpertofuser)
route.post("/hobbie",verifyToken,Hobbies.addhobbie)
route.get("/hobbie",verifyToken,Hobbies.gethobbies)
route.delete("/hobbie",verifyToken,Hobbies.deletehobbies)
route.get("/getimagesprofile",verifyToken,ImagesUser.getallimagesprofile)
route.get("/getUsernameByToken",verifyToken,UserProfile.getUsernameByToken)
route.delete("/",verifyToken,UserProfile.deleteprofile)
route.patch("/updateusername",verifyToken,UserProfile.updatename)
route.patch("/updateapellidop",verifyToken,UserProfile.updateapellidop)
route.patch("/updateapellidom",verifyToken,UserProfile.updataApellidoM)
route.get("/getInformation",verifyToken,UserProfile.getinformation)
route.get("/getInformationById",verifyToken,UserProfile.getInformacionById)
route.patch("/updatesemester",verifyToken,UserProfile.updateNumberSemester)
route.get("/getsocialmediaoptions",verifyToken,UserProfile.getSocialMediaOptions)
route.post("/socialmedia",verifyToken,SocialMedia.addSocialMedia)
route.get("/socialmedia",verifyToken,SocialMedia.getSocialMediaofUser)
route.patch("/socialmedia",verifyToken,SocialMedia.updateSocialmedia)
route.delete("/socialmedia",verifyToken,SocialMedia.deleteSocialMedia)
route.get("/getIdByToken",verifyToken,UserProfile.getIdUserByToken)


module.exports=route